//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WEBApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class phone
    {
        [Required(ErrorMessage ="This field is required to continue")]
        public int Brand_Name { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Model_Name { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Launch { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Camera { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Ram { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Battery { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Network { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string weight { get; set; }
        [Required(ErrorMessage = "This field is required to continue")]
        public string Memory { get; set; }
    }
}
